### ISSUE TITLE
How to use lib with Node.js 

### ISSUE THREAD

**Issue by v-vkov** [konstantin-nizhinskiy/NumberToWords#1]
Hello! I found your library very helpful for my current task. But I have some troubles with usage. Can you support me and explain how to use UA translation in Node.js? 
'Cause for me it doesn't work right. 

My code is here: 
<img width="667" alt="Screenshot 2021-11-30 at 3 57 48 PM" src="https://user-images.githubusercontent.com/53224629/144060584-02abbeb7-1b19-4544-8c31-b18a99061c26.png">

but it still returns me number. 

Thank you!

**Comment by dimitriks** [comment]
Hi. You should import ua locale as shown in the example https://github.com/konstantin-nizhinskiy/NumberToWords#example:
`<script src="dist/translations.ua.js"  type="text/javascript"></script> `
or import at the top of your js-file, like this:
`'import nks-number-to-words/dist/translations/numberToWords.ua';`

**Comment by dimitriks** [comment]
> Hello! I found your library very helpful for my current task. But I have some troubles with usage. Can you support me and explain how to use UA translation in Node.js? 'Cause for me it doesn't work right.
> 
> My code is here: <img alt="Screenshot 2021-11-30 at 3 57 48 PM" width="667" src="https://user-images.githubusercontent.com/53224629/144060584-02abbeb7-1b19-4544-8c31-b18a99061c26.png">
> 
> but it still returns me number.
> 
> Thank you!

Hi. You should import ua locale as shown in the example https://github.com/konstantin-nizhinskiy/NumberToWords#example:
<script src="dist/translations.ua.js" type="text/javascript"></script>
or import at the top of your js-file, like this:
'import nks-number-to-words/dist/translations/numberToWords.ua';
